# Configuration for BD S8 Analysis Pipeline

data:
  excel_path: "data/List of S8 data.xlsx"
  data_folder: "data/converted"  # Folder containing CVW, CZI, or TIFF files
  output_dir: "outputs/"
  
model:
  num_classes: 5
  num_channels: 3
  architecture: "unet_plus_plus"
  encoder: "efficientnet-b4"
  
training:
  batch_size: 4
  num_epochs: 100
  learning_rate: 0.0001
  early_stopping_patience: 10
  
num_workers: 2  # Number of workers for data loading

spillover:
  # Compensation matrix from your Excel notes
  compensation_matrix:
    - [1.0, 0.15, 0.05]   # FITC spillover
    - [0.10, 1.0, 0.08]   # PE spillover
    - [0.02, 0.05, 1.0]   # RB780 spillover
