# config/config.yaml - Updated for REAL data
data:
  # For synthetic/CVW data (OLD)
  excel_path: "data/List of S8 data.xlsx"
  data_folder: "data/"
  
  # For REAL TIFF data (NEW - USE THIS!)
  real_data_root: "/scratch/project_2010376/BDS8/BDS8_data"
  sample_types: ["AML", "Healthy BM"]
  use_real_data: true  # Switch to REAL data
  
model:
  num_classes: 2  # Binary: AML vs Healthy
  num_channels: 3
  encoder: "efficientnet-b0"  # Smaller, faster
  
training:
  batch_size: 32  # Can use larger batch with real data
  num_epochs: 50
  learning_rate: 0.0001
  early_stopping_patience: 10
  num_workers: 8
